version: '3'

services:
  # Backend API service
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
      - ./model:/app/model  # Mount model directory
    environment:
      - MODEL_PATH=/app/model
      - PORT=5000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # Frontend React app
  frontend:
    build:
      context: ./my-app
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./my-app:/app
      - /app/node_modules
    depends_on:
      - api